package testingngservices;

import pairwisetesting.exception.TestCaseTemplateEngineException;
import pairwisetesting.execution.TestCaseTemplateEngine;
import testingngservices.core.TestWorkflow; //Generated by MyEclipse
import testingngservices.sourcefile.ObjectSerializ;
import testingngservices.sourcefile.TestingMetaParameter;

public class TestNGServiceImpl implements ITestNGService {
	private String workPath = "D:/MyShare/Tomcat/";

	public String testExecute(String testingMeta) {
		String result = null;

		TestingMetaParameter temp = (TestingMetaParameter) ObjectSerializ
				.String2Object(testingMeta);
		
		temp.setEndPath(workPath);
		
		TestWorkflow workflow = new TestWorkflow(temp);
		result = workflow.testWorkflow();
		return result;
	}

	public String getTestCase(String methodMeta,String pairwistXML) {
		String testCase = null;
		
		TestCaseTemplateEngine te = new TestCaseTemplateEngine();
		te.setTemplateDir(workPath + "templates");
		te.setPairwiseTestCasesXmlData(pairwistXML);
		te.setTestCaseTemplateParameterXmlData(methodMeta);
		
		try {
			testCase = te.generateTestNGTestCase();
		} catch (TestCaseTemplateEngineException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return testCase;
	}

}