package testingngservices.service;
//Generated by MyEclipse

public interface ITestNGService {
	
	public String testExecute(String testMeta);
	public String getTestCase(String methodMeta,String pairwiseXML);
	public String getLibList();
	public void uploadLib(String lib);
	
}